### ISSUE TITLE
make build failed on mac

### ISSUE THREAD

**Issue by ohari5336** [harness/gitness#3375]
internal/api/usererror/translate.go:27:2: github.com/harness/go-rbac@v0.0.0-20230829014129-c9b217856ea2: invalid version: git ls-remote -q origin in /Users/xyz/go/pkg/mod/cache/vcs/40d64810da2531b923441e2458e47c2849215bcd631e15353e5941e1aca2d37a: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
make: *** [build] Error 1

**Comment by vivekkdagar** [comment]
Are your github credentials correctly configured?

**Comment by johannesHarness** [comment]
Hey @ohari5336, thanks for bringing up this issue, much appreciated!

There seem's to have been a reference left to an internal repository of harness.
I've removed the reference and the issue should be fixed now.

Could you give it another spin? If you run into any issues, please let me know and I'll be happy to take another look!

**Comment by johnmark** [comment]
had the same issue - refreshing the codebase did the trick. Thanks!

**Comment by johannesHarness** [comment]
Awesome, thanks for confirming @johnmark!

**Comment by ohari5336** [comment]
thanks, now build
