### ISSUE TITLE
Gitness on Docker Support/Docs

### ISSUE THREAD

**Issue by egooner** [harness/gitness#3376]
Trying to use the Docker version of GitNess - I have it up and running but.....!!

1. Would be great to have an ARM version of this to run on RPi 4
2. Running up on Intel not sure what port 3001 is for! I assumed SSL but this does not seem to offer SSL connection
3. On creating new REPO for testing the Clone URL shows Localhost:3000 instead of the external address I used via Traefik

I am coming from using Gitea and thought I would give this a try but 3 above is a significant issue which I presume is a matter of an environment variable not set - but I could find not documentation relating to that hence the issue.

**Comment by johannesHarness** [comment]
Hey @egooner, thanks for trying it out, much appreciated!

Those are all very good points, let me try to answer them for you:
1. I agree it makes sense to release images for multiple architectures moving forward, I'll bring that up internally.
2. Great to see you are taking a deeper look into it - in the current architecture we have a package called `gitrpc`, which in a nutshell is a service that allows one to manage/interact with git repositories via gRPC. As of now, gitness starts up its own gitrpc service on port 3001, which is what you see. We are in the works of simplifying this for single binary use-case, as there's no need for making an unnecessary grpc call, we can just call the implementation directly.
3. As you've guessed correctly, there's an environment variable for it. You can set `GITNESS_URL_API="http://{YOUR HOST + PORT}/api`, that should make it work. Let me also bring that up internally so we can add that to the documentation in the future.

I hope that answered your questions :)

**Comment by egooner** [comment]
Thanks for the swift reply - I just tried it and it is still not working. I have exec'd into the Container and can confirm it has the environment set as GITNESS_URL_API="https://mydomainname/api" but the URL in the Clone still shows localhost:3000 (after restarting the Container). I tried creating a new repo and also a new repo in a new project and all of them have the same results.

**Comment by johannesHarness** [comment]
@egooner oh apologies, I missed one. Can you also set `GITNESS_URL_GIT="http://{YOUR HOST + PORT}/git`.
It should also reflect on all existing repos on Gitness

**Comment by egooner** [comment]
Hmm ... any suggestions!! I need to let it know that it is HTTPS otherwise I would try removing the https:// prefix!!
```
gitness: error: encountered an error while wiring the system:  
provided gitURLRaw '"https://mydomainname/git"' is invalid:  
parse "\"https://mydomainname/git\"":  
first path segment in URL cannot contain colon, try --help
```

**Comment by egooner** [comment]
OK - so I tried randomly removing the quotes and it is now OK!!!
```YAML
    environment:
      - "TZ=Europe/London"
      - GITNESS_URL_API=https://mydomainname/api
      - GITNESS_URL_GIT=https://mydomainname/git
```

**Comment by johannesHarness** [comment]
ahhh you were using it in docker-compose file, I see. yes then it would take the double quotes as part of the value.
I was running it with `docker run -e GITNESS_URL_GIT="https://abc/git" ...`.
Let me update my earlier answers to without quotes so other people reading the thread won't get the same issue.
Thanks!

Glad you were able to get it to work :)
