### ISSUE TITLE
Repository privacy

### ISSUE THREAD

**Issue by dhuesca** [harness/gitness#3386]
How can I change a repository visibility?

I can choose if a repo is public or private only on the creation of the repo, I want to change a repository privacy from public to private and there is no mention of how to do that on the docs

**Comment by bradrydzewski** [comment]
@dhuesca great question.  I'm guessing you can probably change this via the API right now, but we definitely need to add this to the repository settings screen.  Let me check with the team and see when we can have this ready.

**Comment by hitesharinga** [comment]
Hey @dhuesca, Thanks for the feedback. 

We just released a new image that allows you to change the `repository visibility` in the settings of a repository. 

You can get the latest image using 
``` docker pull harness/gitness```

Attaching the screenshot of the same. 

![Screenshot 2023-09-28 at 5 36 31 PM](https://github.com/harness/gitness/assets/51195474/00744681-8f90-49d0-89a7-04da283be690)
