### ISSUE TITLE
[Feature request] User Registration control

### ISSUE THREAD

**Issue by MarioGK-AutoSystem** [harness/gitness#3391]
Can we have a feature to disable user registration and only allow manually registered users?

**Comment by johannesHarness** [comment]
Hey @MarioGK-AutoSystem, thank you for your feedback :)

You can already do that today by starting Gitness with the following environment variable:
`GITNESS_USER_SIGNUP_ENABLED=false`

> The the first user on the system can sign-up as normal. Any further user signup will be blocked, and they have to be added manually by an administrator.

We'll also add this to our documentation, soon.
