### ISSUE TITLE
Build arm64 images

### ISSUE THREAD

**Issue by SuNNjek** [harness/gitness#3394]
Right now all the Gitness images on Docker Hub are only built for amd64. It would be cool if we could get arm64 images as well so that the application can be easily deployed on other devices such as Raspberry Pis.

**Comment by johannesHarness** [comment]
Hey @SuNNjek, thank you for your interest in Gitness!
We are working on releasing images for other architectures in the near future.

**Comment by johannesHarness** [comment]
Hey @SuNNjek, good news! We are now releasing Gitness images for both arm64 and amd64, starting from [v3.0.0-beta.3](https://hub.docker.com/layers/harness/gitness/v3.0.0-beta.3/images/sha256-c2fa9f5a03053215bb49845cac786d13d46a620751c57ac283c7c6230d4de3c7?context=explore).
Head over to https://hub.docker.com/r/harness/gitness/tags to see the latest available tags.

**Comment by laxtiz** [comment]
Have you tested it?
Gitness does cross-compiled, but the Git base image is linux/amd64 platform.

> gitness: error: encountered an error while wiring the system: unable to load git version: fork/exec /usr/bin/git: exec format error, try --help

**Comment by enver-bisevac** [comment]
@laxtiz thanks for the feedback, We are able to reproduce the issue and will provide feedback soon.

**Comment by laxtiz** [comment]
the problem at latest step in Dockerfile. finally image must be target platform, should not build platform.

**Comment by enver-bisevac** [comment]
@laxtiz can you try image https://hub.docker.com/r/harness/gitness/tags `unstable` tag?

**Comment by laxtiz** [comment]
@enver-bisevac the `unstable` image is okay,
I created a project, repository, and successfully ran a pipeline task.

but i have a question:
If I do not specify a platform in stages, the amd64 platform is used by default.

https://github.com/harness/gitness/blob/85337b94183f36d4a79b4d3bcec3c539453a38e9/app/pipeline/triggerer/trigger.go#L273-L278

I have used gitea+drone before, and since drone supports multi-node executors, I can understand why the default platform is amd64.
But with gitness being a single node executor, why not set the default platform to `$GOARCH`?

**Comment by laxtiz** [comment]
@vistaarjuneja i mean pipeline runner platform, isn't docker image platform.
You do not need to specify an image platform to obtain container images when pulled.

I am using drone on arm64 platform, if I don't specify the running platform (default amd64), drone-server will show the task as pending.
But on gitness, there are no tasks, it behaves like drone-runner gets tasks from drone-server, but there are no tasks for arm64 platforms, so nothing is done

**Comment by vistaarjuneja** [comment]
@laxtiz we have a poller which requests builds and the trigger that you pointed out above which is submitting builds.  https://github.com/harness/gitness/blob/main/app/pipeline/runner/poller.go#L54 is the filter where you can see that we don't specify an OS and an arch which means that the workers executing builds in gitness are platform agnostic.
And in that scenario we should be skipping the check for the platform completely: https://github.com/harness/gitness/blob/main/app/pipeline/scheduler/queue.go#L167.

So even though we should fix the code you pointed above to just take the machine os/arch in the builds - the workers should still be able to process the builds so I'm curious where the failure is coming 🤔
