### ISSUE TITLE
Pullrequest event (pullreq_closed) missing

### ISSUE THREAD

**Issue by MarioGK-AutoSystem** [harness/gitness#3401]
I did not find any mention of an event for pullrequest close in the code

**Comment by johannesHarness** [comment]
Hey @MarioGK-AutoSystem, thank you for bringing this up!
We'll be adding a `pullreq_closed` trigger for webhooks shortly 🚀

**Comment by tonglil** [comment]
Is this going to be added into Drone or gitness?

There has been a request for this since 2016: https://github.com/harness/gitness/issues/1878

**Comment by abhinav-harness** [comment]
Hey @MarioGK-AutoSystem 
We have merged a [pull request](https://github.com/harness/gitness/commit/1a5c6b06acb7da83151059d0252a5a184dd89ec1) to support both git event and pipeline trigger event for `pullreq_closed` in gitness.  It should be out in the next release.
@tonglil We don't have it planned for drone yet. 

Closing the issue. 
Thanks

**Comment by hitesharinga** [comment]
`pullreq_closed` is released in `harness/gitness:latest` and `harness/gitness:v3.0.0-beta.2`.
