### ISSUE TITLE
Can't import repository from GitHub

### ISSUE THREAD

**Issue by kilyinov** [harness/gitness#3402]
Hi team, trying to import a Spring Petclinic repo (https://github.com/spring-projects/spring-petclinic.git) in Gitness and no luck. This query fails with HTTP 400: http://localhost:3000/api/v1/repos/import
Request: 

`{"description":"","parent_ref":"spring-petclinic","uid":"spring-petclinic.git","provider":{"type":"github","username":"","password":""},"provider_repo":"spring-projects/spring-petclinic.git"}`

Video: https://www.youtube.com/watch?v=v4x6G4BwxhA

**Comment by hitesharinga** [comment]
Hey @kilyinov, 

Thank you for reporting the issue. 

Please update the repository URL to `https://github.com/spring-projects/spring-petclinic`. This change should resolve the problem.
We are working on a modification to allow it to function with `.git` appended to the URL.

Thanks

**Comment by cjlee01** [comment]
Hey @kilyinov,
We have merged a pull request to allow import repo to function with .git appended to the URL. It should be out in the next release.

Closing the issue.
Thanks again!

**Comment by hitesharinga** [comment]
The fix is in `harness/gitness:latest` and `harness/gitness:v3.0.0-beta.2`.
