### ISSUE TITLE
Unable to import repository from GOGS

### ISSUE THREAD

**Issue by emjayit** [harness/gitness#3404]
I too am unable to import a repo, internally hosted on an old GOGS implementation ( Gogs Version: 0.11.91.0811)
The URL is 'http://aurowgit01.rbc.int:3000/mwoodward/Ansible' (also tried appending .git but does not work either)

I get 'Invalid GitHub or GitLab URL'
I have 'requires auth' ticked and username/password entered.

**Comment by avanmathur1** [comment]
Hi @emjayit thank you for your ticket!   We currently only support importing repositories from GitHub or GitLab.  We will update the docs to make this clear, and work on adding support for import from more providers.

**Comment by johannesHarness** [comment]
Hey @emjayit, we've release a new version `v3.0.0-beta.4` which added support to import from gogs.
You can pull the latest image from DockerHub with `docker pull harness/gitness:latest` or `docker pull harness/gitness:v3.0.0-beta.4`
