### ISSUE TITLE
[Feature Request] Code Syntax Color for csharp

### ISSUE THREAD

**Issue by Inerska** [harness/gitness#3419]

**Comment by avanmathur1** [comment]
Hi @Inerska thanks for your feedback.  can you give some more details on what changes you are looking for in syntax colors?

**Comment by Inerska** [comment]
Hello,

Just a basic color syntax for repository's files, when I am looking at a C# file in a repository, it's like plain text, without any color.
It would be pretty good if there would be like a syntax code color.

**Comment by johannesHarness** [comment]
Hey @Inerska, we've added support for csharp syntax highlighting in [this commit](https://github.com/harness/gitness/commit/3ad550ce69a3db84aa3a2a94f52a2c612255d504).
The change should be available as part of our next release.
