### ISSUE TITLE
Sending commits via API

### ISSUE THREAD

**Issue by MarioGK** [harness/gitness#3420]
I am having problems sending commits via api
I am using the following Endpoint [POST] /api/v1/repos/{repo}/commits

The response i am getting is:
```json
{
  "message": "sha does not match for path README.md [given: 3d84e33764a95d00f5b1d4a7c8362580e4fad381, expected: 73a4f96320a42cc62d0271e62aad9213ff165ff1]"
}
```

If it knows the sha already why do we have to send it?

Would it be possible to remove the necessity of sending sha in the request?

**Comment by johannesHarness** [comment]
Hey @MarioGK - thanks for the feedback on the commit API.

The purpose of the SHA is to avoid unintentional overwriting of concurrent changes to the file (it's following the concept of optimistic locking).\
e.g. imagine someone edits the file on the UI, but in the meanwhile someone else changed the file. If such a check wouldn't exist, the user of the UI would now unknowingly overwrite any changes that happened while they were editing the file.

However, I agree that it should be up to the caller to decide whether they want to use optimistic locking or not.
I've merged a change that made the value optional ([commit](https://github.com/harness/gitness/commit/adeb965723edf8fa1658236225861c0f38289590)).

The change should be available as part of the next release.

**Comment by MarioGK** [comment]
Thank you @johannesHarness, i will be waiting for the new release

**Comment by johannesHarness** [comment]
Hey @MarioGK, we've release a new version `v3.0.0-beta.4` which contains the above mentioned change - the file SHA in our COMMIT API is now optional.
You can pull the latest image from DockerHub with `docker pull harness/gitness:latest` or `docker pull harness/gitness:v3.0.0-beta.4`
