### ISSUE TITLE
Gitness website Contribution 

### ISSUE THREAD

**Issue by lebe24** [harness/gitness#3439]
Hi, gitness team your website is awesome and cool I would like to have the opportunity to contribute 😃 but I am finding it difficult to find the gitness.com repo. I would appreciate the assistance cloning the repo of it is open source.

**Comment by bradrydzewski** [comment]
I am glad to hear you like the website and appreciate the offer to contribute, however, the gitness.com website is not open source at this time.

**Comment by lebe24** [comment]
Guess I will have to reverse-engineer it then. Thanks by the way
