### ISSUE TITLE
Simultaneously support multiple version control systems

### ISSUE THREAD

**Issue by wmvm0** [harness/gitness#3444]
Simultaneously support multiple version control systems

I use github, gitlab on one drone。but now only on valid

**Comment by avanmathur1** [comment]
Hi @wmvm0 .  thank you for your feedback, we are working on adding support for all git providers, we will keep you updated on this.

**Comment by wmvm0** [comment]
> Hi @wmvm0 . thank you for your feedback, we are working on adding support for all git providers, we will keep you updated on this.

What I mean is that while the service is running, multiple code hosting platforms are supported simultaneously.

The current code is like this

`func provideClient(config config.Config) *scm.Client {
	switch {
	case config.Bitbucket.ClientID != "":
		return provideBitbucketClient(config)
	case config.Github.ClientID != "":
		return provideGithubClient(config)
	case config.Gitee.ClientID != "":
		return provideGiteeClient(config)
	case config.Gitea.Server != "":
		return provideGiteaClient(config)
	case config.GitLab.ClientID != "":
		return provideGitlabClient(config)
	case config.Gogs.Server != "":
		return provideGogsClient(config)
	case config.Stash.ConsumerKey != "":
		return provideStashClient(config)
	}
	logrus.Fatalln("main: source code management system not configured")
	return nil
}`

Only one code hosting platform can exist at a time，I want to be able to use github and bitbucket at the same time, my code is in multiple places

**Comment by bradrydzewski** [comment]
yes, unlike Drone 1.x and Drone 2.x, Gitness (aka Drone 3.x) was re-architected to support multiple providers per installation. The implementation, however, is still a work in progress.

**Comment by wmvm0** [comment]
> yes, unlike Drone 1.x and Drone 2.x, Gitness (aka Drone 3.x) was re-architected to support multiple providers per installation. The implementation, however, is still a work in progress.

OK, I understand, thank you very much
