### ISSUE TITLE
How to config the domain for gitness?

### ISSUE THREAD

**Issue by huabin** [harness/gitness#3445]
Hello everyone, 

I run a gitness via docker, and I want to change this url. 
<img width="766" alt="errd" src="https://github.com/harness/gitness/assets/535675/655626e1-abd1-4de4-a154-1303476b94d0">
I checked the gitness docs, but I didn't find how. Can anyone help? Thank you so mcuh.

**Comment by indaco** [comment]
You should use the `GITNESS_URL_BASE` env var. Check here, [Configuration](https://docs.gitness.com/reference/configuration#gitness_url_base). Hope it helps

**Comment by huabin** [comment]
@indaco Great, thank you so much.
