### ISSUE TITLE
How to DELETE “Import in progress...” Repositories

### ISSUE THREAD

**Issue by zhqagp** [harness/gitness#3452]
How to DELETE “Import in progress...” Repositories

<img width="1233" alt="image" src="https://github.com/harness/gitness/assets/6457312/fdd6b669-57ac-41f0-b22f-99c6ddad7afa">

Translation status lasted two days

**Comment by hitesharinga** [comment]
Hey @zhqagp, We will add support for delete.

**Comment by hitesharinga** [comment]
Hey @zhqagp, We have added option to delete in-progress repos. Thanks for reporting.
