### ISSUE TITLE
[docs] set GITNESS_PRINCIPAL_ADMIN_EMAIL

### ISSUE THREAD

**Issue by indaco** [harness/gitness#3453]
with docker image `harness/gitness:latest` after the [remove default Admin account /environment variables](https://github.com/harness/gitness/commit/4c90cec3e59d9218a606c4b533688ff96569503f), the [doc page](https://docs.gitness.com/installation/settings) should be update to include the newly required `GITNESS_PRINCIPAL_ADMIN_EMAIL` env var 

```bash
docker run -d \
  -e GITNESS_PRINCIPAL_ADMIN_EMAIL=mail@example.com \ 
  -e GITNESS_PRINCIPAL_ADMIN_PASSWORD=correct-horse-battery-staple \
  -e GITNESS_USER_SIGNUP_ENABLED=false \
  -p 3000:3000 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/gitness:/data \
  --name gitness \
  --restart always \
  harness/gitness
```

Otherwise:

> gitness: error: encountered an error while bootstrapping the system: failed to setup admin user: failed to set up admin user: config.Principal.Admin.Email is required, try --help

**Comment by jimsheldon** [comment]
Thanks @indaco for catching this.

We have updated the settings section with this new requirement https://docs.gitness.com/installation/settings
