### ISSUE TITLE
[docs] missing env variables

### ISSUE THREAD

**Issue by indaco** [harness/gitness#3454]
First,
I'm loving gitness and would like to thank all for your work. 

There are a lot of possible configuration via ENV vars defined in [types/config.go](https://github.com/harness/gitness/blob/main/types/config.go) but most are not [documented](https://docs.gitness.com/installation/settings) at all. 

Would be great if all are listed and documented accordingly or if you accept PR for documentation 

Thanks

**Comment by hitesharinga** [comment]
Hey @indaco, 

Thank you for bringing this to our attention. We're delighted to hear that you're loving it. 

We have documented configs https://docs.gitness.com/installation/settings. Let us know if you are looking for some specific configs which we can document.

**Comment by indaco** [comment]
Hey @hitesharinga 
Thanks for getting back to me on that. 

You all are doing an amazing work
