### ISSUE TITLE
[BUG] Pipeline runtime record label is missing

### ISSUE THREAD

**Issue by holdlg** [harness/gitness#3468]
Pipeline runtime record label is missing.
version: 3.0.0-beta.5
![image](https://github.com/harness/gitness/assets/4408716/d81bc8a8-005e-4b45-abfa-d2b90054cbe6)

**Comment by johannesHarness** [comment]
@holdlg thanks for bringing this up! The problem should be fixed in the latest release.
If you still encounter the above problem, please reopen the issue.
