### ISSUE TITLE
Credentials not needed from localhost

### ISSUE THREAD

**Issue by Nahiiko** [harness/gitness#3469]
Hi,

Is it normal that I'm able to clone a private repo without any credentials using `git clone http://192.168.X.XXX:5555/git/test/testrepo.git` ? Seems quite insecure to me.

It is working as intended (or so it seems) if I try `git clone https://gitness.mywebsite.com/git/test/testrepo.git` meaning I cannot clone without the credentials.

I tried using https (just in case that was the reason somehow) didn't change anything, it seems even using the flag `GITNESS_HTTP_PROTO=https` didn't change anything ? I could still access the instance using http only, and https did not resolve.

so three questions arise:
- Why isn't the https flag working (or so it seems)
- Would a working https config enforce the credentials usage ?
- Why does the issue exist in the first place, shouldn't credentials be required all the time ?

My docker-compose:

> name: gitness
> services:
>     gitness:
>         ports:
>             - 5555:3000
>         volumes:
>             - /volume1/docker/gitness/data:/data
>         container_name: gitness
>         restart: always
>         image: harness/gitness
>         environment:
>           - GITNESS_USER_SIGNUP_ENABLED=false
>           - GITNESS_URL_BASE=https://gitness.mywebsite.com
>           - GITNESS_ENCRYPTER_SECRET=myencryptionkey

**Comment by bradrydzewski** [comment]
>Why isn't the https flag working (or so it seems)

setting the https flag is not enough. you need to configure ssl certificates

> Would a working https config enforce the credentials usage

no, https has no bearing on whether or not credentials are required to clone

> Why does the issue exist in the first place, shouldn't credentials be required all the time ?

it shouldn't.  if it exists it would be a regression.  I've send to our engineers and asked them to research further.  they should have an answer shortly.

**Comment by hitesharinga** [comment]
Hey @Nahiiko,

Could you verify if the repository is set to public? On the repository listing page, each repository is labeled as either public or private.

If it's private, please delete the token from the profile page and attempt the action again.

**Comment by hitesharinga** [comment]
Hey @Nahiiko , 

Credentials are shared across Repos and projects.

**Comment by bradrydzewski** [comment]
Thanks @Nahiiko for providing additional details and thanks @hitesharinga for jumping in to troubleshoot.

Similar to a GitHub personal token or Gitlab personal token, your Gitness personal token is tied to your user account. This means the token can be used to clone any repository to which your account has access.  It sounds like this has been clarified, so closing.  We can re-open if needed.
