### ISSUE TITLE
Drone does not support 3-level or above path's repositories?

### ISSUE THREAD

**Issue by hongyuxuan** [harness/gitness#3472]
When installed the Drone server for GitLab, I cannot find and synchronize repositories with a 3-level or above paths. 
For example, 
repo1: https://gitlab.cicconline.com/group1/project1 ------ yes I can find and sync it
repo2: https://gitlab.cicconline.com/group1/project2 ------ yes I can find and sync it
repo3: https://gitlab.cicconline.com/group1/group2/project3 ------ no I cannot find and sync it
repo4: https://gitlab.cicconline.com/group1/group2/group3/project4 ------ no I cannot find and sync it

I'm sure I have read/write priviledges of the repositories above. ( I can see them in gitlab )

I have already followed all the steps of https://docs.drone.io/server/provider/gitlab/, I created a gitlab `Applications` with scope of `api` and `read_user`

drone-serve version: 2.22.0

**Comment by Arsolitt** [comment]
same
