### ISSUE TITLE
Feature: Support SurrealDB

### ISSUE THREAD

**Issue by itsezc** [harness/gitness#3473]
SurrealDB is a great fit for Gitness, as it can act as a file based storage alternative to SQLite or a full blown database and an alternative to Postgres. While it is early days for both projects, I think it would be great to start new deployments of Gitness with SurrealDB and for users who use Gitness with Surreal they'll have an easy time scaling up from file based Surreal to distributed Surreal as their usage of gitness scales.

Currently there is a Go library for Surreal: https://github.com/surrealdb/surrealdb.go

**Comment by bradrydzewski** [comment]
thanks for the suggestion, however, we are not looking to expand database support at this time.
