### ISSUE TITLE
[BUG] Unable to import repository from GitHub when branch name is not 'main'

### ISSUE THREAD

**Issue by KevinYouu** [harness/gitness#3474]
I encountered an issue where importing a repository from GitHub fails when the branch name is not 'main'. The import process consistently displays Import in progress.... Additionally, when I commit locally with a branch name other than 'main', the committed code appears empty after submission.
<img width="897" alt="截屏2024-02-11 22 22 36" src="https://github.com/harness/gitness/assets/46970005/81ddaa75-e757-4791-bca5-2127169dfe60">

**Comment by flowck** [comment]
I tried it out of curiosity and I was able to successfully import a repository.

Repo imported: https://github.com/beego/beego

```
docker run -d \
  -p 3000:3000 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/gitness:/data \
  --name gitness \
  --restart always \
  harness/gitness
```

![Screenshot 2024-02-14 at 20 04 59](https://github.com/harness/gitness/assets/1679333/60cf5449-942b-4802-ac59-e009bbce33b3)

**Comment by KevinYouu** [comment]
> I tried it out of curiosity and I was able to successfully import a repository.
> 
> Repo imported: https://github.com/beego/beego
> 
> ```
> docker run -d \
>   -p 3000:3000 \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   -v /tmp/gitness:/data \
>   --name gitness \
>   --restart always \
>   harness/gitness
> ```
> 
> ![Screenshot 2024-02-14 at 20 04 59](https://private-user-images.githubusercontent.com/1679333/304861263-60cf5449-942b-4802-ac59-e009bbce33b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjk0MzUsIm5iZiI6MTcwODMyOTEzNSwicGF0aCI6Ii8xNjc5MzMzLzMwNDg2MTI2My02MGNmNTQ0OS05NDJiLTQ4MDItYWM1OS1lMDA5YmJjZTMzYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDc1MjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGYzZWFiMWQ4YTFiMGQ2MmQwOGIyMTFkNzY1ZmJlZjYwNzQxODc0NjJiMTdhYzkzNTdjNTJhMWRhMmI5NmMxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yKs81wDZX0KNpiKdR_CV7ab0GVkltiETfVXnFhE8hfc)

I'm deploying using docker-compose on Debian 12 operating system. Below is the configuration file. I'm encountering issues importing GitHub repositories.
```yaml
version: '3'
services:
  gitness:
    container_name: gitness
    image: harness/gitness
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/gitness:/data
    restart: unless-stopped
```
<img width="899" alt="image" src="https://github.com/harness/gitness/assets/46970005/a0ea3240-9734-4d55-8aa2-deb5dae523dc">

**Comment by abolast** [comment]
`
services:
  gitness:
    image: harness/gitness
    container_name: gitness
    ports:
      - "3009:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/abola/Documents/docker-compose-gitanyway/data:/data
    restart: always
    networks:
      gitea2:
        ipv4_address: 172.22.0.6
`
unable to import repository too. i tried from gogs and gitea.

**Comment by zzinx58** [comment]
The same, Bad experience, sad..

**Comment by zzinx58** [comment]
This issue could cause by using proxy i guess this is the point.
After set Organization Name as my github username:zzinx58,
Repository name: [projectName].git
I am able to come to the next step.

**Comment by hitesharinga** [comment]
Hey @KevinYouu, Thanks for reporting the issue. 
I tried to import the repo you mentioned and was able to import it successfully. 
On the second issue - We have added support to update the default branch in the first commit if the first commit is not in the default branch. 

Please reopen if you face the issue.
