### ISSUE TITLE
Opensource Website?

### ISSUE THREAD

**Issue by Mateoo303** [harness/gitness#3513]
Is your `https://gitness.com/` website opensource? I can't find it anywhere. I'm really curios how did you make all animations on that website. They are impresive and I thought I could learn from it. 
Assuming that website is not open source, which tools did you use to make those animations in `canvas`?
Thanks for you time.

**Comment by bradrydzewski** [comment]
Glad to hear you like the website.  We use a third party firm to design and manage our website, so unfortunately we (the Gitness developers) don't really have much experience / knowledge with the tools they used.  With that being said, the design firm does post extensively about their work on Twitter. They frequently discuss tooling and sometimes even post tutorials.  See https://twitter.com/alex_barashkov
