### ISSUE TITLE
Gitness Integration with Open Source Dev Environment Manager.

### ISSUE THREAD

**Issue by Rutik7066** [harness/gitness#3524]
Hi, I am working on project. I want to add support for gitness to be added as git-provider.
I am facing one small problem where I need to fetch Organizations via API. 
I have checked all swagger APIs. but did not find useful. I don't even know does gitness support Organizations like github?
Can anyone tell me how do I fetch Organizations via API?

**Comment by bradrydzewski** [comment]
yes, Gitness supports the concept of organizations, however, in Gitness they are called "spaces".  You can use the `/api/v1/user/memberships` endpoint to get a list of all spaces to which the user belongs.

**Comment by Rutik7066** [comment]
can you provide a documentation link for spaces?
