### ISSUE TITLE
Gitness Api

### ISSUE THREAD

**Issue by Rutik7066** [harness/gitness#3526]
I am having a problem fetching all repos of the project and personal repos (I don't know if gitness supports personal repos which do not belong to any project but only belong to the user like GitHub). I have checked all endpoints, but unfortunately, I did not find anything useful.

**Comment by bradrydzewski** [comment]
The short answer is no.

Like GitHub, all repositories in Gitness must belong to a namespace (e.g. `github.com/bradrydzewski` would be the equivalent of `gitness.com/bradrydzewski`).  The main different is that GitHub creates a namespace automatically for every user account and GItness does not.  If you want a personal namespace in Gitness, you would create a project with only you as the member.

**Comment by Rutik7066** [comment]
How do I fetch all repositories belonging to the project?

**Comment by bradrydzewski** [comment]
This is the endpoint for returning a list of all project (space) repositories

```
http://localhost:3000/api/v1/spaces/{space}/+/repos?page=1&limit=20
```

Note that the Gitness user interface uses the API.  So when in doubt, you can use Chrome Developer Tools to determine which endpoints are being called to fetch data.

<img width="1041" alt="Screenshot 2024-06-04 at 10 47 35 AM" src="https://github.com/harness/gitness/assets/817538/a205bcf9-aee3-45c3-965a-e67f6a4a2c2e">

There is also an interactive Swagger frontend that you can use to explore the API

```
http://localhost:3000/swagger#/space/listRepos
```
