### ISSUE TITLE
Bug: browse the files within the "search" directory.

### ISSUE THREAD

**Issue by ysicing** [harness/gitness#3530]
![image](https://github.com/harness/gitness/assets/8605565/0ed6af76-f6ac-4d47-80a9-1fcda94ce2cf)

![image](https://github.com/harness/gitness/assets/8605565/39401a7d-f3c0-4ac9-9a7f-e27987c10ac2)

When there is a "search" directory in the repository, it is not possible to browse the files within the "search" directory.

**Comment by marko-gacesa** [comment]
Yes, this is a bug. Thank you for reporting. We are working on the fix.
