### ISSUE TITLE
Support LFS

### ISSUE THREAD

**Issue by prishacoder** [harness/gitness#3536]
Hello Team,

Gitness local setup is very smooth. I have few questions:

1. How should I use S3 in Fitness to store the git repository to save on storage cost?
2. To manage LFS files does Gitness have any integration with Git-LFS or DVC?

Thanks!

**Comment by bradrydzewski** [comment]
Gitness does not yet support LFS.  This is something we want to support in the future, however, it is not something we are actively working on at the moment.  We will update back to this issue once we have an update.

**Comment by bradrydzewski** [comment]
Combining with Issue #3465

**Comment by prishacoder** [comment]
@bradrydzewski Thank you for the response!

1. How should I use S3 to store the git repository to save on storage cost? Is it possible in Gitness or is there any direction that I can follow? Does repository also get stored in PostgreSQL or it get stored in local disk?

2. Also, I have an existing Auth and RBAC for my app can I disable the Gitness Auth and RBAC and use own or is there any way I can establish communication between my existing app and Gitness?
