### ISSUE TITLE
How to use Gitness as headless without UI?

### ISSUE THREAD

**Issue by prishacoder** [harness/gitness#3537]
Hello Team,

For my requirement, I want to use Gitness in a headless form, utilizing only the backend without the UI. I've tried removing the web package and the web image build steps, but this results in errors. It appears that the backend router imports web and openapi components.

How can I gracefully disable these components? Is there a way to remove the UI and solely use the backend APIs of Gitness for programmatic consumption?

**Comment by bradrydzewski** [comment]
Running Gitness in headless mode is not currently supported / not something we plan to support in the future. You would need to fork the project and modify to fit your needs.
