### ISSUE TITLE
How to use S3 or GCS to store repos?

### ISSUE THREAD

**Issue by prishacoder** [harness/gitness#3538]
How can I configure S3 storage in Gitness to store Git repositories? I noticed that GCS is configured in this repository: https://github.com/harness/gitness/tree/main/blob. Is it used for storing repositories? If so, which environment variables or paths need to be configured to mount S3-compatible storage for storing the Git repositories?

**Comment by johannesHarness** [comment]
Hey @prishacoder, that's a good question.
The `blob` package that you are referring to is currently used for storing PR description / comment artifacts (e.g. images and videos).

As for storing git repositories, we currently only support file system. Adding new storage options is not prioritized at this time.

As possible alternative, you could take a look at mounting S3 buckets to your local file system using [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse) and then store your repositories there (Disclaimer: This has not been tested)
