### ISSUE TITLE
Cannot commit to the newly created repo

### ISSUE THREAD

**Issue by kevinthant** [harness/gitness#3553]
Hi 

I run the Gitness app locally by pulling in the latest code from the `main` branch and compiling it but fail to push any commits to the newly created repository through Gitness web GUI.  Every time I push changes to the repository, it fails with no detailed information. However, in the console log of the Gitness server running locally, I see the error messages as seen in the screenshot below. Can anyone please advise what I am doing wrong? Thanks!

<img width="963" alt="image" src="https://github.com/user-attachments/assets/5946c6dd-c73a-498f-b669-bf86b7272e5f">

**Comment by karansaraswat19** [comment]
Hey @kevinthant 
Thanks for reporting this issue!
You will need to update your git to 2.43.2 or above

**Comment by kevinthant** [comment]
Thank you so much, it resolved my issue @karansaraswat19
