### ISSUE TITLE
api for Projects missing?

### ISSUE THREAD

**Issue by moorthi07** [harness/gitness#3556]
REST apis for 'Projects' not available in swagger. Is it intentionally left or any plan to add in near future?

**Comment by abhinav-harness** [comment]
Hey @moorthi07 
On backend we call projects as spaces, you can find all APIs for project under it. 
Thanks

**Comment by moorthi07** [comment]
HI @abhinav-harness , II'm asking about project under project management, I guess not the dev spaces if I understand correctly. Here is the link
https://docs.gitness.com/administration/project-management

**Comment by moorthi07** [comment]
Ok just found 'Spaces' apis . But fyi: confusing with 'gitspaces'
